import pandas as pd
import os

start = "4"
end = "370"
add_start = "310"
add_end = "330"
york = "York*"
wash = "Washington*"
set = "Set*"
locations = [york,wash,set]

top_left = 29

setwashyork  = { 'colLoc':[      "Scheduled","Set","Washington","York","","","Not Yet Performed","Set","Washington","York","","","Completed","Set","Washington","York",""],
                 'colPCR':[      "PCRs",
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=set,type="PCR"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR"),
                                 "=SUM($E${top}:$E${bot})".format(top=top_left+1,bot=top_left+3),
                                 "",
                                 "PCRs Left",
                                 '=COUNTIFS($C${start}:$C${end}, "<>y", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=set,type="PCR"),
                                 '=COUNTIFS($C${start}:$C${end}, "<>y", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR"),
                                 '=COUNTIFS($C${start}:$C${end}, "<>y", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR"),
                                 "=SUM($E${top}:$E${bot})".format(top=top_left+7,bot=top_left+9),
                                 "",
                                 "PCRs Completed",
                                 '=COUNTIFS($C${start}:$C${end}, "y", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $K${add_start}:$K${add_end}, "{location}", $L${add_start}:$L${add_end}, "{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=set,type="PCR"),
                                 '=COUNTIFS($C${start}:$C${end}, "y", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $K${add_start}:$K${add_end}, "{location}", $L${add_start}:$L${add_end}, "{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR"),
                                 '=COUNTIFS($C${start}:$C${end}, "y", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $K${add_start}:$K${add_end}, "{location}", $L${add_start}:$L${add_end}, "{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR"),
                                 "=SUM($E${top}:$E${bot})".format(top=top_left+13,bot=top_left+15)],
                  'colRPCR':[    "PCR + Rs",
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=set,type="PCR + R"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR + R"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR + R"),
                                 "=SUM($F${top}:$F${bot})".format(top=top_left+1,bot=top_left+3),
                                 "",
                                 "PCR + Rs Left",
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") - COUNTIFS($C${start}:$C${end}, "y", $B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=set,type="PCR + R"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") - COUNTIFS($C${start}:$C${end}, "y", $B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR + R"),
                                '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") - COUNTIFS($C${start}:$C${end}, "y", $B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR + R"),
                                 "=SUM($F${top}:$F${bot})".format(top=top_left+7,bot=top_left+9),
                                 "",
                                 "PCR + Rs Completed",
                                 '=COUNTIFS($C${start}:$C${end}, "y", $B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=set,type="PCR + R"),
                                 '=COUNTIFS($C${start}:$C${end}, "y", $B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR + R"),
                                 '=COUNTIFS($C${start}:$C${end}, "y", $B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR + R"),
                                 "=SUM($F${top}:$F${bot})".format(top=top_left+13,bot=top_left+15)],
                  'colRapid':[   "Rapids",
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=set,type="Rapid"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="Rapid"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="Rapid"),
                                 "=SUM($G${top}:$G${bot})".format(top=top_left+1,bot=top_left+3),
                                 "",
                                 "Rapids Left",
                                 '=COUNTIFS($B${start}:$B${end}, "<>r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=set,type="Rapid"),
                                 '=COUNTIFS($B${start}:$B${end}, "<>r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="Rapid"),
                                 '=COUNTIFS($B${start}:$B${end}, "<>r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="Rapid"),
                                 "=SUM($G${top}:$G${bot})".format(top=top_left+7,bot=top_left+9),
                                 "",
                                 "Rapids Completed",
                                 '=COUNTIFS($B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=set,type="Rapid"),
                                 '=COUNTIFS($B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="Rapid"),
                                 '=COUNTIFS($B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="Rapid"),
                                 "=SUM($G${top}:$G${bot})".format(top=top_left+13,bot=top_left+15)],
                 'colTotal':[    "Total Tests Done",
                                 "=SUM($E${top}:$G${top})".format(top=top_left+1),
                                 "=SUM($E${mid}:$G${mid})".format(mid=top_left+2),
                                 "=SUM($E${bot}:$G${bot})".format(bot=top_left+3),
                                 "=SUM($E${tot}:$G${tot})".format(tot=top_left+4),
                                 "",
                                 "Total Yet to Be Performed",
                                 "=SUM($E${top}:$G${top})".format(top=top_left+7),
                                 "=SUM($E${mid}:$G${mid})".format(mid=top_left+8),
                                 "=SUM($E${bot}:$G${bot})".format(bot=top_left+9),
                                 "=SUM($E${tot}:$G${tot})".format(tot=top_left+10),
                                 "",
                                 "Total Tests Done",
                                 "=SUM($E${top}:$G${top})".format(top=top_left+13),
                                 "=SUM($E${mid}:$G${mid})".format(mid=top_left+14),
                                 "=SUM($E${bot}:$G${bot})".format(bot=top_left+15),
                                 "=SUM($E${tot}:$G${tot})".format(tot=top_left+16)]
     }

washyork     = { 'colLoc':[      "Scheduled","Washington","York","","","Not Yet Performed","Washington","York","","","Completed","Washington","York",""],
                 'colPCR':[      "PCRs",
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR"),
                                 "=SUM($E${top}:$E${bot})".format(top=top_left+1,bot=top_left+2),
                                 "",
                                 "PCRs Left",
                                 '=COUNTIFS($C${start}:$C${end}, "<>y", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR"),
                                 '=COUNTIFS($C${start}:$C${end}, "<>y", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR"),
                                 "=SUM($E${top}:$E${bot})".format(top=top_left+6,bot=top_left+7),
                                 "",
                                 "PCRs Completed",
                                 '=COUNTIFS($C${start}:$C${end}, "y", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $K${add_start}:$K${add_end}, "{location}", $L${add_start}:$L${add_end}, "{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR"),
                                 '=COUNTIFS($C${start}:$C${end}, "y", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $K${add_start}:$K${add_end}, "{location}", $L${add_start}:$L${add_end}, "{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR"),
                                 "=SUM($E${top}:$E${bot})".format(top=top_left+11,bot=top_left+12)],
                  'colRPCR':[    "PCR + Rs",
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR + R"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR + R"),
                                 "=SUM($F${top}:$F${bot})".format(top=top_left+1,bot=top_left+2),
                                 "",
                                 "PCR + Rs Left",
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") - COUNTIFS($C${start}:$C${end}, "y", $B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR + R"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") - COUNTIFS($C${start}:$C${end}, "y", $B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR + R"),
                                 "=SUM($F${top}:$F${bot})".format(top=top_left+6,bot=top_left+7),
                                 "",
                                 "PCR + Rs Completed",
                                 '=COUNTIFS($C${start}:$C${end}, "y", $B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="PCR + R"),
                                 '=COUNTIFS($C${start}:$C${end}, "y", $B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($C${add_start}:$C${add_end}, "y", $B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="PCR + R"),
                                 "=SUM($F${top}:$F${bot})".format(top=top_left+11,bot=top_left+12)],
                  'colRapid':[   "Rapids",
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="Rapid"),
                                 '=COUNTIFS($K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="Rapid"),
                                 "=SUM($G${top}:$G${bot})".format(top=top_left+1,bot=top_left+2),
                                 "",
                                 "Rapids Left",
                                 '=COUNTIFS($B${start}:$B${end}, "<>r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="Rapid"),
                                 '=COUNTIFS($B${start}:$B${end}, "<>r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="Rapid"),
                                 "=SUM($G${top}:$G${bot})".format(top=top_left+6,bot=top_left+7),
                                 "",
                                 "Rapids Completed",
                                 '=COUNTIFS($B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=wash,type="Rapid"),
                                 '=COUNTIFS($B${start}:$B${end}, "r", $K${start}:$K${end}, "{location}", $L${start}:$L${end},"{type}") + COUNTIFS($B${add_start}:$B${add_end}, "r", $K${add_start}:$K${add_end}, "{location}",$L${add_start}:$L${add_end},"{type}")'.format(start=start,end=end,add_start=add_start,add_end=add_end,location=york,type="Rapid"),
                                 "=SUM($G${top}:$G${bot})".format(top=top_left+11,bot=top_left+12)],
                 'colTotal':[    "Total Tests Done",
                                 "=SUM($E${top}:$G${top})".format(top=top_left+1),
                                 "=SUM($E${mid}:$G${mid})".format(mid=top_left+2),
                                 "=SUM($E${bot}:$G${bot})".format(bot=top_left+3),
                                 "",
                                 "Total Yet to Be Performed",
                                 "=SUM($E${top}:$G${top})".format(top=top_left+6),
                                 "=SUM($E${mid}:$G${mid})".format(mid=top_left+7),
                                 "=SUM($E${bot}:$G${bot})".format(bot=top_left+8),
                                 "",
                                 "Total Tests Done",
                                 "=SUM($E${top}:$G${top})".format(top=top_left+9),
                                 "=SUM($E${mid}:$G${mid})".format(mid=top_left+10),
                                 "=SUM($E${bot}:$G${bot})".format(bot=top_left+11)]
     }

frame = pd.DataFrame(data=washyork)

print(frame)
frame.to_csv("./outgooglesheetformulas.csv")
